version: '3.8'

services:
  sender:
    build:
      context: ./sender
      dockerfile: Dockerfile
    container_name: mqtt-sender-${HOSTNAME}-${VERSION_DOCKER}
    restart: unless-stopped
    ports:
      - "4815:4815"
    volumes:
      - ./data:/app/data
      - ./certs:/app/certs
    env_file:
      - .env
    environment:
      - BROKER_HOST=192.168.18.110
    networks:
      - iot_network

  simulator:
    build:
      context: ./simulator
      dockerfile: Dockerfile
    container_name: simulator-${HOSTNAME}-${VERSION_DOCKER}
    restart: unless-stopped
    environment:
      - SENDER_HOST=mqtt-sender-${HOSTNAME}-${VERSION_DOCKER}
    depends_on:
      - sender
    networks:
      - iot_network

networks:
  iot_network:
    driver: bridge